## CHANGE this to the name of your plugin.
name: SlimefunAddon

## CHANGE this to your username.
author: Apeiros

## CHANGE this to a meaninful but short description of your plugin.
description: My entry to the 2021 Slimefun Addon Jam

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.Apeiros.slimefunaddon.SlimefunAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Apeiros-46B/AddonJam2021Entry

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
