## CHANGE this to the name of your plugin.
name: AlchimiaVitae

## CHANGE this to your username.
author: Apeiros

## CHANGE this to a meaninful but short description of your plugin.
description: Slimefun addon that adds magic, alchemy and herbalism

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.apeiros.alchimiavitae.AlchimiaVitae

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.17

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun